uploads = []

[[generated]]
id = "-yx9JdfyfuIL7Gt6r2IZH"
uri = "file://artifacts/artisan-sn/public/hero-bg.png"
type = "image"
title = "Dakar market hero background"

[[generated]]
id = "BkVrfSBuTMa43Q0HQctju"
uri = "file://artifacts/artisan-sn/public/plumber.png"
type = "image"
title = "Plumber working"

[[generated]]
id = "nrD-5Tja0tqf4ywoGJ_LC"
uri = "file://artifacts/artisan-sn/public/tailor.png"
type = "image"
title = "Tailor working"

[[generated]]
id = "dcKrbGVKjvs07z04iobRY"
uri = "file://attached_assets/generated_images/generated_image.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8T6T0IwNAvbeU5CqTbEoi"
uri = "file://artifacts/artisan-sn/public/pwa-512x512.png"
type = "image"
title = "teranga services app icon"

[[outputs]]
id = "FHyGXu-bAy1YhcrF4QBfJ"
uri = "file://artifacts/artisan-sn/public/affiche-sunu-artisans.png"
type = "image"
title = "Affiche promotionnelle Sunu Artisans"
